//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jQuery_AJAX_WebAPI_CRUD_MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserDetails = new HashSet<UserDetail>();
            this.UserSessions = new HashSet<UserSession>();
        }
    
        public int Id { get; set; }
        public string DomainName { get; set; }
        public string UserIP { get; set; }
        public string Source { get; set; }
        public string Location { get; set; }
        public string mobile { get; set; }
        public string os { get; set; }
        public string browser { get; set; }
    
        public virtual ICollection<UserDetail> UserDetails { get; set; }
        public virtual ICollection<UserSession> UserSessions { get; set; }
    }
}
